[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

#[[plugins]]
#repo = 'hrsh7th/vim-vsnip'

#[[plugins]]
#repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	let g:airline#extensions#branch#enabled = 1
	let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
	./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
	let g:previm_open_cmd = 'open -a Google\ Chrome'
'''

[[plugins]]
repo = 'ryym/vim-viler'
hook_add = '''
	function! s:configure_viler_buffer() abort
	  nnoremap <buffer><nowait> <CR> :<C-u>call viler#open_cursor_file('edit')<CR>
	  nmap <buffer><nowait> <C-l> <Plug>(viler-open-file)
	  nmap <buffer><nowait> <C-h> <Plug>(viler-cd-up)
	  nmap <buffer><nowait> t <Plug>(viler-toggle-tree)
	endfunction
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
hook_add = '''
	let g:cursorhold_updatetime = 100
'''

[[plugins]]
repo = 'zztkm/nipo.vim'
